[package]
name = "erased-serde-explanation"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
publish = false

[[bin]]
name = "erased-serde-explanation"
path = "main.rs"
